In [1]:
import urllib
import requests
import time
from flask import Flask, request

In [2]:
# Necessary imports:
import json
import pandas as pd
from pandas.plotting import parallel_coordinates
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import random
import os
import csv

# Setting up current directory:
CURRENT_DIRECTORY = os.getcwd() 

In [3]:
# Importing data from a csv file

# male = 1, female = 0
# race A = 0, race B = 1, race C = 2, race D = 3
# some hs = 0, high school = 1, some college = 2, associate's = 3, bacherlor's = 4, master's = 5
# free/reduced = 0, standard = 1
# no prep = 0, completed prep = 1

dataset = pd.read_csv(CURRENT_DIRECTORY + "/StudentsPerformance.csv")

dataset["id"] = range(1000)

feature_columns = ["gender", "race", "parental_education", "lunch", "prep"]
X = dataset[feature_columns].values
print(X)
Y = dataset['score'].values

[[0 1 4 1 0]
 [0 2 2 1 1]
 [0 1 5 1 0]
 ...
 [0 2 1 0 1]
 [0 3 2 1 1]
 [0 3 2 0 0]]


In [4]:
# Splitting into training and test datasets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0)

# Creating the learning model
knn_classifier = KNeighborsClassifier(n_neighbors=50)

# Fitting the model with the training data
knn_classifier.fit(X_train, Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=50, p=2,
           weights='uniform')

In [5]:
# Making predictions with the test data (This line is also where we would potentially classify new data)
Y_pred = knn_classifier.predict(X_test)
print(Y_pred)
print(Y_test)

def accuracy(test, pred):
    tot = 0
    for pred_score, actual_score in zip(test, pred):
        diff = abs(pred_score - actual_score)
        acc = diff / float(pred_score)
        tot += acc
    return 1 - (tot / len(test))

# Finding Accuracy:
accuracy = accuracy(Y_test, Y_pred)*100
print('Accuracy of model: ' + str(round(accuracy, 2)) + ' %.')

[53 55 54 65 74 82 72 53 76 79 74 58 77 53 60 51 62 61 50 67 61 53 72 83
 71 55 59 82 51 75 54 67 46 67 66 53 86 67 72 74 60 54 68 68 68 72 67 65
 86 78 53 60 54 67 68 53 53 71 76 53 71 66 74 53 68 57 79 67 82 60 71 71
 79 68 71 71 86 79 75 68 67 88 88 68 71 68 71 75 74 78 68 67 58 67 60 67
 68 58 46 62 82 71 49 73 53 70 70 61 74 79 74 68 53 86 68 68 48 86 75 82
 53 54 75 62 68 66 80 74 76 68 79 60 68 86 67 53 71 65 77 60 71 75 60 67
 54 60 54 68 50 60 59 68 66 68 75 65 71 74 77 68 80 77 68 53 66 68 52 67
 60 60 77 68 65 68 74 60 65 67 68 60 82 68 48 67 74 79 72 88 78 59 59 67
 60 72 60 65 43 68 85 68 71 86 68 77 68 51 75 68 76 61 68 77 54 68 54 53
 75 80 55 77 60 79 60 72 60 65 68 79 61 65 51 58 54 67 46 86 74 76 76 65
 68 72 72 59 82 68 46 56 86 68 86 67 74 54 60 54 53 74 54 68 67 76 71 80
 54 68 71 75 68 77 76 86 60 73 67 60 59 67 72 68 59 67 75 72 82 60 68 50
 66 54 68 48 79 59 74 73 74 67 77 53]
[ 69  77  45  67  74  73  70  43  89  38  51  64  83  81  54  39  52  86
  53  79  63 

In [6]:
def make_prediction(X):
    Y_pred = knn_classifier.predict(X)
    return Y_pred
        

In [ ]:
app = Flask(__name__)

@app.route("/", methods=['GET'])
def predict():
    g = int(request.args.get("gender"))
    r = int(request.args.get("race"))
    pe = int(request.args.get("parental_education"))
    l = int(request.args.get("lunch"))
    pr = int(request.args.get("prep"))
    
    X = [[g,r,pe,l,pr]]
    ans = 0
    
    pred = make_prediction(X)
    for score in pred:
        ans = int(score)
    return str("This person is predicted to score " + str(ans))
    
app.run()
# male = 1, female = 0
# race A = 0, race B = 1, race C = 2, race D = 3
# some hs = 0, high school = 1, some college = 2, associate's = 3, bacherlor's = 4, master's = 5
# free/reduced = 0, standard = 1
# no prep = 0, completed prep = 1

# Example:
# http://127.0.0.1:5000/?gender=1&race=2&parental_education=5&lunch=1&prep=1
# Scores a projected 86

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [30/Oct/2019 01:33:00] "GET /?gender=1&race=0&parental_education=5&lunch=1&prep=1 HTTP/1.1" 200 -
127.0.0.1 - - [30/Oct/2019 01:33:10] "GET /?gender=1&race=0&parental_education=0&lunch=1&prep=1 HTTP/1.1" 200 -
127.0.0.1 - - [30/Oct/2019 01:33:10] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Oct/2019 01:33:15] "GET /?gender=1&race=0&parental_education=0&lunch=1&prep=0 HTTP/1.1" 200 -
127.0.0.1 - - [30/Oct/2019 01:33:15] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Oct/2019 01:33:19] "GET /?gender=1&race=0&parental_education=4&lunch=1&prep=0 HTTP/1.1" 200 -
127.0.0.1 - - [30/Oct/2019 01:33:19] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Oct/2019 01:33:22] "GET /?gender=1&race=0&parental_education=3&lunch=1&prep=0 HTTP/1.1" 200 -
127.0.0.1 - - [30/Oct/2019 01:33:22] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [30/Oct/2019 01:33:25] "GET /?gender=1&race=0&parental_education=2&lunch=1&prep=0 